# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [2]:
import numpy as np
data = np.arange(1,11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [3]:
import numpy as np
data = np.zeros((3,3))
print(data)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [4]:
import numpy as np
data = np.linspace(0,5,10)
print(data)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [5]:
data = np.eye(5,5)
print(data)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [6]:
data = np.random.rand(4,4)
print(data)

[[0.16206296 0.62685867 0.25925353 0.21383039]
 [0.85078246 0.89588403 0.94121659 0.07296067]
 [0.82553912 0.89791105 0.82871585 0.49415234]
 [0.54245408 0.40259075 0.84862064 0.60387766]]


---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [7]:
data = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(data.shape)

(3, 3)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [8]:
data = np.arange(16)
print(data)
data = data.reshape((4,4))
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [9]:
print(data.dtype)

int64


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [10]:
data = np.arange(1,101)
print(data[data%2==0])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [11]:
data = np.random.randint(10,50,(6,6))
print(data)

[[31 37 28 13 42 35]
 [22 22 32 45 31 25]
 [38 19 10 40 42 10]
 [45 20 15 46 16 14]
 [28 11 19 42 24 38]
 [34 16 19 29 12 41]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [12]:
print(data[1:3, 2:5])

[[32 45 31]
 [10 40 42]]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [13]:
print(np.sum(data))

991


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [14]:
print("mean: ", np.mean(data), "std:", np.std(data), "median: ", np.median(data))

mean:  27.52777777777778 std: 11.39075188014653 median:  28.0


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [15]:
print("max: ", np.max(data), "min: ", np.min(data))

max:  46 min:  10


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [16]:
data = np.random.randint(1,20,10)
print(data)
print(np.argmax(data))

[13 17  1  8  3 15 10 10  3 11]
1


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [17]:
data = data[::-1]
print(data)

[11  3 10 10 15  3  8  1 17 13]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [18]:
data1 = np.random.rand(3,3)
data2 = np.random.rand(3,3)
print(data1*data2)

[[0.12516407 0.01443594 0.03490136]
 [0.43687373 0.12233213 0.15897566]
 [0.08392679 0.91283204 0.46422183]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [19]:
data = np.diag([1,1,1,1])
print(data)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [20]:
data1*data2

array([[0.12516407, 0.01443594, 0.03490136],
       [0.43687373, 0.12233213, 0.15897566],
       [0.08392679, 0.91283204, 0.46422183]])

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [21]:
data1.flatten()

array([0.23276861, 0.91247536, 0.16295214, 0.44018177, 0.14274436,
       0.32514658, 0.33745601, 0.98179066, 0.87005224])

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [22]:
np.vstack((data1, data2))

array([[0.23276861, 0.91247536, 0.16295214],
       [0.44018177, 0.14274436, 0.32514658],
       [0.33745601, 0.98179066, 0.87005224],
       [0.53771886, 0.01582063, 0.21418167],
       [0.99248483, 0.85700149, 0.48893536],
       [0.24870438, 0.92976239, 0.53355628]])

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [23]:
np.hstack((data1,data2))

array([[0.23276861, 0.91247536, 0.16295214, 0.53771886, 0.01582063,
        0.21418167],
       [0.44018177, 0.14274436, 0.32514658, 0.99248483, 0.85700149,
        0.48893536],
       [0.33745601, 0.98179066, 0.87005224, 0.24870438, 0.92976239,
        0.53355628]])

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [24]:
np.split(data1,3)

[array([[0.23276861, 0.91247536, 0.16295214]]),
 array([[0.44018177, 0.14274436, 0.32514658]]),
 array([[0.33745601, 0.98179066, 0.87005224]])]

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [25]:
np.round(6*np.random.rand(6,6),2)

array([[1.07, 1.71, 1.21, 0.63, 0.16, 3.93],
       [4.03, 3.94, 5.14, 5.85, 3.48, 5.57],
       [5.82, 0.63, 1.01, 5.29, 3.91, 3.13],
       [1.36, 5.03, 4.28, 1.99, 4.13, 1.17],
       [1.66, 3.69, 1.17, 1.55, 3.13, 3.9 ],
       [4.55, 4.87, 3.62, 5.56, 4.16, 4.33]])

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [26]:
np.unique(data)

array([0, 1])

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [27]:
data[data<=0.5] = 4
print(data)

[[1 4 4 4]
 [4 1 4 4]
 [4 4 1 4]
 [4 4 4 1]]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [28]:
print(data)
np.cumsum(data)

[[1 4 4 4]
 [4 1 4 4]
 [4 4 1 4]
 [4 4 4 1]]


array([ 1,  5,  9, 13, 17, 18, 22, 26, 30, 34, 35, 39, 43, 47, 51, 52])

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [29]:
len(data[data!=0])

16

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [30]:
np.sort(data, True,)

array([[1, 4, 4, 4],
       [1, 4, 4, 4],
       [1, 4, 4, 4],
       [1, 4, 4, 4]])

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [31]:
data = np.random.rand(3,3)
print(data.sum(axis=1),data.sum(axis=0))

[0.90194673 0.95220088 1.72483167] [0.96463454 1.50615363 1.10819111]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [32]:
data =np.random.randint(10,100, (6,6))
print(data)
data = data/np.max(data)
print(data)

[[41 68 72 67 74 44]
 [33 26 37 41 38 72]
 [14 17 36 19 43 92]
 [81 65 49 26 87 93]
 [90 30 29 72 46 57]
 [46 12 29 43 57 67]]
[[0.44086022 0.7311828  0.77419355 0.72043011 0.79569892 0.47311828]
 [0.35483871 0.27956989 0.39784946 0.44086022 0.40860215 0.77419355]
 [0.15053763 0.1827957  0.38709677 0.20430108 0.46236559 0.98924731]
 [0.87096774 0.69892473 0.52688172 0.27956989 0.93548387 1.        ]
 [0.96774194 0.32258065 0.31182796 0.77419355 0.49462366 0.61290323]
 [0.49462366 0.12903226 0.31182796 0.46236559 0.61290323 0.72043011]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [33]:
data1 = np.random.randint(10,100, (6,6))
data2 = np.random.randint(10,100, (6,6))
np.dot(data1,data2)

array([[21319, 13210, 21834, 15130, 13101, 16746],
       [23439, 14361, 21090, 14192, 12421, 14276],
       [22051, 12990, 19485, 12674, 10351, 11897],
       [16671, 10418, 18082, 10638, 10545, 14067],
       [24520, 17118, 25094, 16135, 15318, 19075],
       [16562,  9830, 20871, 15115, 10525, 15902]])

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [34]:
np.trace(data1)

390

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [35]:
data = np.random.randint(10,100, (6,6))
print(data)
a = data[1,].copy()
data[1,] = data[2,]
data[2,] = a
print(data)

[[12 10 73 57 24 53]
 [55 98 63 59 76 46]
 [44 66 73 17 19 69]
 [96 42 33 17 89 14]
 [95 93 26 63 34 53]
 [72 11 80 46 29 67]]
[[12 10 73 57 24 53]
 [44 66 73 17 19 69]
 [55 98 63 59 76 46]
 [96 42 33 17 89 14]
 [95 93 26 63 34 53]
 [72 11 80 46 29 67]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [36]:
data = np.arange(10)
print(data)
print(data.shape)
data.shape = (1,10)
data

[0 1 2 3 4 5 6 7 8 9]
(10,)


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [37]:
data = np.random.randint(10, 20, (3,3))
np.linalg.det(data)

-318.0

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [38]:
data = np.random.randint(10, 100, (2,2))
print(np.linalg.eigvals(data))
print(np.linalg.eig(data))

[133.12729212  30.87270788]
(array([133.12729212,  30.87270788]), array([[ 0.76358229, -0.65314675],
       [ 0.64571052,  0.75723135]]))


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [39]:
data = np.random.randint(10, 100, (3,3))
np.linalg.solve(data, np.arange(3))

array([-0.440903  ,  0.16671404,  0.34276666])

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [40]:
data =  np.random.normal(0,1,100)
data

array([-4.60468376e-01, -6.15198558e-01, -4.00436125e-01,  6.54230472e-01,
        1.39628832e+00,  2.61585173e-01,  1.45361988e+00, -1.21533618e+00,
        3.34016174e-01, -1.50636010e+00,  9.41362948e-01, -2.98246464e-01,
        9.79834141e-01,  5.30569420e-01, -1.18039336e+00,  1.14830850e+00,
       -1.05811712e+00, -7.71815758e-01,  1.01391121e+00, -1.19089102e+00,
        8.17531039e-01,  3.36167996e-01, -9.38707139e-02,  4.15164193e-01,
        9.14013118e-01, -3.10975407e-01, -3.28173658e-01, -3.79840927e-01,
        1.50928296e-01, -2.83279157e-01, -4.34311980e-01, -2.62498205e-01,
        7.01236241e-01,  9.21014135e-01,  1.68895346e-01,  1.05414706e+00,
        7.75802280e-02, -2.49945054e-01, -6.51268897e-01, -9.34390810e-01,
       -3.36465524e-01,  4.92283329e-01,  1.12404570e+00, -6.68417262e-01,
        9.81741167e-01,  8.42592589e-01, -3.75487434e-01, -6.94813899e-01,
        7.83534323e-01, -2.35578543e+00, -5.30810924e-01, -2.91985198e-01,
       -6.86728921e-01, -

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [41]:
data = np.random.randint(1,10,(4,4))
np.diagonal(data)

array([5, 3, 3, 2])

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

In [50]:

data = np.random.rand(100)
np.clip(data, 10,50)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10.])

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

In [51]:
data = np.arange(-5,10)
data[data<0]=0
data

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

In [55]:
print(np.inner(data1, data2))
print(np.outer(data1, data2))

[[14552 13349 26272 17274 15328 18607]
 [13391 13610 25234 15877 17170 17923]
 [12675 12506 22903 13118 17252 15844]
 [11288  7498 20424 13329 10926 13220]
 [15805 12283 29459 19244 15928 20100]
 [15543 12917 23222 14548 13983 14793]]
[[4774 3080 4235 ... 2310 4928 5621]
 [1860 1200 1650 ...  900 1920 2190]
 [1550 1000 1375 ...  750 1600 1825]
 ...
 [6076 3920 5390 ... 2940 6272 7154]
 [ 930  600  825 ...  450  960 1095]
 [2542 1640 2255 ... 1230 2624 2993]]


---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---